name: Actions workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Actions
        id: greet
        uses: actions/hello-world-javascript-action@master@v1
        with:
          who-to-greet: "Mona the Octocat"
      - name: log greeting time
      - run: echo "${{steps.greet.outputs.time}}"
