name: Actions workflow
on: [push, pull_request]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: List files
        run: |
          pwd 
          ls -a
      - name: Actions
        id: greet
        uses: actions/hello-world-javascript-action@master
        with:
          who-to-greet: "Mona the Octocat"
      - name: log greeting time
        run: echo "${{steps.greet.outputs.time}}"
