name: Slack Demo
on: push
env:
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
jobs:
  log-env:
    runs-on: ubuntu-latest
    steps:
      - name: Pipeline complete
        id: Pipeline complete
        uses: act10ns/slack@v1
        with:
          status: ${{job.status}}
        if: always()
      - uses: act10ns/slack@v1
        name: Steps
        id: Steps
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
