name: Environments
on: push
env:
  WF_ENV: available to all jobs

jobs:
  log-env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: only for steps
    steps:
      - name: log env varibale hello
        env:
          STEP_ENV: only for the step
        run: |
          echo "WF_ENF:  ${WF_ENV}"
          echo "JOBS: ${JOB_ENV}"
          echo "STEPS: ${STEP_ENV}"
      - name: Restricted variables
        env:
          STEP_ONLY: STEP_ONLY
        run: |
          echo "WF_ENF:  ${WF_ENV}"
          echo "JOBS: ${JOB_ENV}"
          echo "STEPS: ${STEP_ENV}"
          echo "STEPS_Only: ${STEP_ONLY}"
