name: Shell CMD
on: [push]

jobs:
  run-shell-cmd:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
    steps:
      - name: echo hello
        run: echo hello world
      - name: multi line scrip
        run: |
          node -v
          npm -v
          echo ${SLACK_WEBHOOK_URL}
      - name: python cmd
        run: |
          import platform
          print (platform.processor())
        shell: python
      - uses: actions/slack@v1
        name: Slack
        with:
          status: ${{ job.status }}
          channel: "#test"
